### ISSUE TITLE
Cannot npm install

### ISSUE THREAD

**Issue by akmur** [apexcharts/react-apexcharts#204]
I would like to run the development environment.

When I `npm install` I get a bunch of warnings, like:

```
npm WARN tar ENOENT: no such file or directory, open '/Users/amuraro/Projects/react-apexcharts/node_modules/.staging/source-map-adc61990/lib/source-node.js'
```

and in the end

```
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/amuraro/.npm/_logs/2020-08-06T10_09_56_258Z-debug.log
```

When I look in the log, the warning and errors I see are:

```
14270 warn react-apexcharts@1.3.7 requires a peer of apexcharts@^3.18.0 but none is installed. You must install peer dependencies yourself.
14271 warn react-apexcharts@1.3.7 No repository field.
14272 verbose stack RangeError: Maximum call stack size exceeded
14272 verbose stack     at RegExp.test (<anonymous>)
14272 verbose stack     at isDepOptional (/Users/amuraro/.asdf/installs/nodejs/12.18.2/lib/node_modules/npm/lib/install/deps.js:425:27)
14272 verbose stack     at failedDependency (/Users/amuraro/.asdf/installs/nodejs/12.18.2/lib/node_modules/npm/lib/install/deps.js:441:9)
14272 verbose stack     at failedDependency (/Users/amuraro/.asdf/installs/nodejs/12.18.2/lib/node_modules/npm/lib/install/deps.js:457:9)
14272 verbose stack     at failedDependency (/Users/amuraro/.asdf/installs/nodejs/12.18.2/lib/node_modules/npm/lib/install/deps.js:457:9)
14272 verbose stack     at failedDependency (/Users/amuraro/.asdf/installs/nodejs/12.18.2/lib/node_modules/npm/lib/install/deps.js:457:9)
14272 verbose stack     at failedDependency (/Users/amuraro/.asdf/installs/nodejs/12.18.2/lib/node_modules/npm/lib/install/deps.js:457:9)
14272 verbose stack     at failedDependency (/Users/amuraro/.asdf/installs/nodejs/12.18.2/lib/node_modules/npm/lib/install/deps.js:457:9)
14272 verbose stack     at failedDependency (/Users/amuraro/.asdf/installs/nodejs/12.18.2/lib/node_modules/npm/lib/install/deps.js:457:9)
14272 verbose stack     at failedDependency (/Users/amuraro/.asdf/installs/nodejs/12.18.2/lib/node_modules/npm/lib/install/deps.js:457:9)
14272 verbose stack     at failedDependency (/Users/amuraro/.asdf/installs/nodejs/12.18.2/lib/node_modules/npm/lib/install/deps.js:457:9)
14272 verbose stack     at failedDependency (/Users/amuraro/.asdf/installs/nodejs/12.18.2/lib/node_modules/npm/lib/install/deps.js:457:9)
14272 verbose stack     at failedDependency (/Users/amuraro/.asdf/installs/nodejs/12.18.2/lib/node_modules/npm/lib/install/deps.js:457:9)
14272 verbose stack     at failedDependency (/Users/amuraro/.asdf/installs/nodejs/12.18.2/lib/node_modules/npm/lib/install/deps.js:457:9)
14272 verbose stack     at failedDependency (/Users/amuraro/.asdf/installs/nodejs/12.18.2/lib/node_modules/npm/lib/install/deps.js:457:9)
14272 verbose stack     at failedDependency (/Users/amuraro/.asdf/installs/nodejs/12.18.2/lib/node_modules/npm/lib/install/deps.js:457:9)
14273 verbose cwd /Users/amuraro/Projects/react-apexcharts
14274 verbose Darwin 19.6.0
14275 verbose argv "/Users/amuraro/.asdf/installs/nodejs/12.18.2/bin/node" "/Users/amuraro/.asdf/installs/nodejs/12.18.2/bin/npm" "install"
14276 verbose node v12.18.2
14277 verbose npm  v6.14.5
14278 error Maximum call stack size exceeded
14279 verbose exit [ 1, true ]
```

Any idea?

**Comment by junedchhipa** [comment]
Have you installed both `react-apexcharts` as well as `apexcharts`?

**Comment by akmur** [comment]
right, i didn't see i had to install apexcharts myself, I thought it was being installed along with the rest, thanks!
