### ISSUE TITLE
Uncaught (in promise) TypeError: t.className.match is not a function

### ISSUE THREAD

**Issue by Madeindreams** [apexcharts/react-apexcharts#230]
This error is showing a lot in the console. When I load or resize the the chart

linkifyContentScript.bundle.js:1 Uncaught (in promise) TypeError: t.className.match is not a function
    at c (linkifyContentScript.bundle.js:1)
    at u (linkifyContentScript.bundle.js:1)
    at linkifyContentScript.bundle.js:1
    at i (linkifyContentScript.bundle.js:1)
    at l._tryToStartAnother (linkifyContentScript.bundle.js:1)
    at l._next (linkifyContentScript.bundle.js:1)
    at i (linkifyContentScript.bundle.js:1)

What does it mean?

Anytime I interact with apexchart displays it raise this error. When I hover it to.
You can see it live here with a metamask wallet on rinkeby
[here](https://madeindreams.ca/dex)

I'm using react-apexchart

**Comment by ajmeese7** [comment]
I'm getting this exact error as well, but this package isn't a dependency of the project I inherited! No clue where it's coming from, the error trace isn't making it easy:

```log
Uncaught (in promise) TypeError: t.className.match is not a function
    at linkifyContentScript.bundle.js:1:22042
    at a (linkifyContentScript.bundle.js:1:22207)
    at linkifyContentScript.bundle.js:1:23058
    at linkifyContentScript.bundle.js:1:16523
    at q.M (linkifyContentScript.bundle.js:1:19402)
    at q.P (linkifyContentScript.bundle.js:1:18683)
    at linkifyContentScript.bundle.js:1:17556
```
