### ISSUE TITLE
renders return empty when testing with jest

### ISSUE THREAD

**Issue by oyemini-fortifieddata** [apexcharts/react-apexcharts#260]
I'm testing a component with react testing library and jest. and I dont seem to be able to render the chart.

I saw a similar issue [here ](https://github.com/apexcharts/react-apexcharts/issues/197) that helped me pass the first error (r.node.getBBox is not a function), but now the render just return empty. I would have created an example on codesandbox but they don't support the jest.mock feature yet.

**my test file is based on the example from the linked issue like so:**

```
import '@testing-library/jest-dom'
import { render, screen } from '@testing-library/react'
import ReactApexChart from "react-apexcharts";

jest.mock('react-apexcharts', () => jest.fn(() => { return null }));
jest.mock('apexcharts', () => ({ exec: jest.fn(() => { return new Promise((resolve) => { resolve("uri") }) }) }));


test.only('Renders OK', async () => {

    const state = {
        options: {
            chart: {
                type: 'candlestick',
                height: 350
            },
            title: {
                text: 'CandleStick Chart',
                align: 'left'
            },
            xaxis: {
                type: 'datetime'
            },
            yaxis: {
                tooltip: {
                    enabled: true
                }
            }
        },
        series: [{
            name: 'series-1',
            data: [{
                x: new Date(1538778600000),
                y: [6629.81, 6650.5, 6623.04, 6633.33]
            },
            {
                x: new Date(1538780400000),
                y: [6632.01, 6643.59, 6620, 6630.11]
            },
            {
                x: new Date(1538782200000),
                y: [6630.71, 6648.95, 6623.34, 6635.65]
            },
            {
                x: new Date(1538784000000),
                y: [6635.65, 6651, 6629.67, 6638.24]
            },
            {
                x: new Date(1538785800000),
                y: [6638.24, 6640, 6620, 6624.47]
            },
            {
                x: new Date(1538787600000),
                y: [6624.53, 6636.03, 6621.68, 6624.31]
            },
            {
                x: new Date(1538789400000),
                y: [6624.61, 6632.2, 6617, 6626.02]
            },
            {
                x: new Date(1538791200000),
                y: [6627, 6627.62, 6584.22, 6603.02]
            },
            {
                x: new Date(1538793000000),
                y: [6605, 6608.03, 6598.95, 6604.01]
            },
            {
                x: new Date(1538794800000),
                y: [6604.5, 6614.4, 6602.26, 6608.02]
            },
            {
                x: new Date(1538796600000),
                y: [6608.02, 6610.68, 6601.99, 6608.91]
            },
            ]
        }]
    };


    render(<ReactApexChart
        options={state.options}
        series={state.series}
        type="candlestick"
        width={800}
        height={350}
    />);

    screen.debug();
    expect(await screen.findByText('CandleStick Chart')).toBeInTheDocument();

});
```

**and this is the error I get:**

`mockConstructor(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.

       95 | 
       96 | 
    >  97 |     render(<ReactApexChart
          |     ^
       98 |         options={state.options}
       99 |         series={state.series}
      100 |         type="candlestick"

      at reconcileChildFibers (node_modules/react-dom/cjs/react-dom.development.js:14169:23)
      at reconcileChildren (node_modules/react-dom/cjs/react-dom.development.js:16990:28)
      at mountIndeterminateComponent (node_modules/react-dom/cjs/react-dom.development.js:17890:5)       
      at beginWork (node_modules/react-dom/cjs/react-dom.development.js:19049:16)
      at HTMLUnknownElement.callCallback (node_modules/react-dom/cjs/react-dom.development.js:3945:14)   
      at HTMLUnknownElement.callTheUserObjectsOperation (node_modules/jsdom/lib/jsdom/living/generated/EventListener.js:26:30)
      at innerInvokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:318:25)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)     
      at HTMLUnknownElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:221:9)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:94:17)
      at HTMLUnknownElement.dispatchEvent (node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:231:34)
      at Object.invokeGuardedCallbackDev (node_modules/react-dom/cjs/react-dom.development.js:3994:16)   
      at invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:4056:31)
      at beginWork$1 (node_modules/react-dom/cjs/react-dom.development.js:23964:7)
      at performUnitOfWork (node_modules/react-dom/cjs/react-dom.development.js:22779:12)
      at workLoopSync (node_modules/react-dom/cjs/react-dom.development.js:22707:5)
      at renderRootSync (node_modules/react-dom/cjs/react-dom.development.js:22670:7)
      at performSyncWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:22293:18)
      at scheduleUpdateOnFiber (node_modules/react-dom/cjs/react-dom.development.js:21881:7)
      at updateContainer (node_modules/react-dom/cjs/react-dom.development.js:25482:3)
      at node_modules/react-dom/cjs/react-dom.development.js:26021:7
      at unbatchedUpdates (node_modules/react-dom/cjs/react-dom.development.js:22431:12)
      at legacyRenderSubtreeIntoContainer (node_modules/react-dom/cjs/react-dom.development.js:26020:5)  
      at Object.render (node_modules/react-dom/cjs/react-dom.development.js:26103:10)
      at node_modules/@testing-library/react/dist/pure.js:99:25
      at batchedUpdates$1 (node_modules/react-dom/cjs/react-dom.development.js:22380:12)
      at act (node_modules/react-dom/cjs/react-dom-test-utils.development.js:1042:14)
      at render (node_modules/@testing-library/react/dist/pure.js:95:26)
      at Object.<anonymous> (src/tests/FDChart.test.js:97:5)`

**Comment by sofiset** [comment]
@oyemini-fortifieddata Was having the same issue, this worked for me: 

```
jest.mock('react-apexcharts', () => {
  return {
    __esModule: true,
    default: () => {
      return <div />
    },
  }
})
```

**Comment by PacoFMD** [comment]
@oyemini-fortifieddata did you solved the problem using testing library with react-apexchart?

**Comment by justinfarrelldev** [comment]
> @oyemini-fortifieddata Was having the same issue, this worked for me:
> 
> ```
> jest.mock('react-apexcharts', () => {
>   return {
>     __esModule: true,
>     default: () => {
>       return <div />
>     },
>   }
> })
> ```

Just wanted to add that this also worked for me. I ran into an issue at first: 
```
The module factory of `jest.mock()` is not allowed to reference any out-of-scope variables. Invalid variable access: __jsxFileName
```
However,  I was simply using `jest.mock` incorrectly. If anyone runs into this, try pulling out the `jest.mock` to the global scope above the functions (I was using it in a `beforeAll` which is incorrect).

Just adding this in case anyone else makes the same silly mistake.
