### ISSUE TITLE
Cannot read property 'node' of undefined

### ISSUE THREAD

**Issue by tkosiorski** [apexcharts/react-apexcharts#399]
Welcome! 
I am getting this error while firing up the tests.
Besides, the component works as it should, even in the storybook.
Are you able to help me?

**Codesandbox**
[https://codesandbox.io/s/frosty-proskuriakova-u20g21?file=/src/ChartOptions.tsx](codesandbox)

Cannot read property 'node' of undefined
TypeError: Cannot read property 'node' of undefined
    at t.value (C:\Scout\is24-finance-portal\node_modules\apexcharts\dist\apexcharts.common.js:12004:68)
    at t.value (C:\Scout\is24-finance-portal\node_modules\apexcharts\dist\apexcharts.common.js:11994:665)
    at t.value (C:\Scout\is24-finance-portal\node_modules\apexcharts\dist\apexcharts.common.js:12117:29)
    at r.value (C:\Scout\is24-finance-portal\node_modules\react-apexcharts\dist\react-apexcharts.min.js:1:4213)
    at callComponentWillUnmountWithTimer (C:\Scout\is24-finance-portal\node_modules\react-dom\cjs\react-dom.development.js:20413:14)
    at HTMLUnknownElement.callCallback (C:\Scout\is24-finance-portal\node_modules\react-dom\cjs\react-dom.development.js:3945:14)
    at HTMLUnknownElement.callTheUserObjectsOperation (C:\Scout\is24-finance-portal\node_modules\jsdom\lib\jsdom\living\generated\EventListener.js:26:30)
    at innerInvokeEventListeners (C:\Scout\is24-finance-portal\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:338:25)
    at invokeEventListeners (C:\Scout\is24-finance-portal\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:274:3)
    at HTMLUnknownElementImpl._dispatch (C:\Scout\is24-finance-portal\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:221:9)
    at HTMLUnknownElementImpl.dispatchEvent (C:\Scout\is24-finance-portal\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:94:17)
    at HTMLUnknownElement.dispatchEvent (C:\Scout\is24-finance-portal\node_modules\jsdom\lib\jsdom\living\generated\EventTarget.js:231:34)
    at Object.invokeGuardedCallbackDev (C:\Scout\is24-finance-portal\node_modules\react-dom\cjs\react-dom.development.js:3994:16)
    at invokeGuardedCallback (C:\Scout\is24-finance-portal\node_modules\react-dom\cjs\react-dom.development.js:4056:31)
    at safelyCallComponentWillUnmount (C:\Scout\is24-finance-portal\node_modules\react-dom\cjs\react-dom.development.js:20420:5)
    at commitUnmount (C:\Scout\is24-finance-portal\node_modules\react-dom\cjs\react-dom.development.js:20951:11)
    at commitNestedUnmounts (C:\Scout\is24-finance-portal\node_modules\react-dom\cjs\react-dom.development.js:21004:5)
    at unmountHostComponents (C:\Scout\is24-finance-portal\node_modules\react-dom\cjs\react-dom.development.js:21290:7)
    at commitDeletion (C:\Scout\is24-finance-portal\node_modules\react-dom\cjs\react-dom.development.js:21347:5)
    at commitMutationEffects (C:\Scout\is24-finance-portal\node_modules\react-dom\cjs\react-dom.development.js:23407:11)
    at HTMLUnknownElement.callCallback (C:\Scout\is24-finance-portal\node_modules\react-dom\cjs\react-dom.development.js:3945:14)
    at HTMLUnknownElement.callTheUserObjectsOperation (C:\Scout\is24-finance-portal\node_modules\jsdom\lib\jsdom\living\generated\EventListener.js:26:30)
    at innerInvokeEventListeners (C:\Scout\is24-finance-portal\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:338:25)
    at invokeEventListeners (C:\Scout\is24-finance-portal\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:274:3)
    at HTMLUnknownElementImpl._dispatch (C:\Scout\is24-finance-portal\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:221:9)
    at HTMLUnknownElementImpl.dispatchEvent (C:\Scout\is24-finance-portal\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:94:17)
    at HTMLUnknownElement.dispatchEvent (C:\Scout\is24-finance-portal\node_modules\jsdom\lib\jsdom\living\generated\EventTarget.js:231:34)
    at Object.invokeGuardedCallbackDev (C:\Scout\is24-finance-portal\node_modules\react-dom\cjs\react-dom.development.js:3994:16)
    at invokeGuardedCallback (C:\Scout\is24-finance-portal\node_modules\react-dom\cjs\react-dom.development.js:4056:31)
    at commitRootImpl (C:\Scout\is24-finance-portal\node_modules\react-dom\cjs\react-dom.development.js:23121:9)
    at unstable_runWithPriority (C:\Scout\is24-finance-portal\node_modules\scheduler\cjs\scheduler.development.js:468:12)
    at runWithPriority$1 (C:\Scout\is24-finance-portal\node_modules\react-dom\cjs\react-dom.development.js:11276:10)
    at commitRoot (C:\Scout\is24-finance-portal\node_modules\react-dom\cjs\react-dom.development.js:22990:3)
    at performSyncWorkOnRoot (C:\Scout\is24-finance-portal\node_modules\react-dom\cjs\react-dom.development.js:22329:3)
    at scheduleUpdateOnFiber (C:\Scout\is24-finance-portal\node_modules\react-dom\cjs\react-dom.development.js:21881:7)
    at updateContainer (C:\Scout\is24-finance-portal\node_modules\react-dom\cjs\react-dom.development.js:25482:3)
    at legacyRenderSubtreeIntoContainer (C:\Scout\is24-finance-portal\node_modules\react-dom\cjs\react-dom.development.js:26037:5)
    at C:\Scout\is24-finance-portal\node_modules\react-dom\cjs\react-dom.development.js:26147:7
    at unbatchedUpdates (C:\Scout\is24-finance-portal\node_modules\react-dom\cjs\react-dom.development.js:22431:12)
    at Object.unmountComponentAtNode (C:\Scout\is24-finance-portal\node_modules\react-dom\cjs\react-dom.development.js:26146:5)
    at C:\Scout\is24-finance-portal\node_modules\@testing-library\react\dist\pure.js:144:23
    at batchedUpdates$1 (C:\Scout\is24-finance-portal\node_modules\react-dom\cjs\react-dom.development.js:22380:12)
    at act (C:\Scout\is24-finance-portal\node_modules\react-dom\cjs\react-dom-test-utils.development.js:1042:14)
    at cleanupAtContainer (C:\Scout\is24-finance-portal\node_modules\@testing-library\react\dist\pure.js:143:26)
    at Set.forEach (<anonymous>)
    at cleanup (C:\Scout\is24-finance-portal\node_modules\@testing-library\react\dist\pure.js:137:21)
    at Object.<anonymous> (C:\Scout\is24-finance-portal\node_modules\@testing-library\react\dist\index.js:33:25)
    at Promise.then.completed (C:\Scout\is24-finance-portal\node_modules\jest-circus\build\utils.js:276:28)
    at new Promise (<anonymous>)
    at callAsyncCircusFn (C:\Scout\is24-finance-portal\node_modules\jest-circus\build\utils.js:216:10)
    at _callCircusHook (C:\Scout\is24-finance-portal\node_modules\jest-circus\build\run.js:175:40)
    at _runTest (C:\Scout\is24-finance-portal\node_modules\jest-circus\build\run.js:152:5)
    at _runTestsForDescribeBlock (C:\Scout\is24-finance-portal\node_modules\jest-circus\build\run.js:63:9)
    at _runTestsForDescribeBlock (C:\Scout\is24-finance-portal\node_modules\jest-circus\build\run.js:57:9)
    at run (C:\Scout\is24-finance-portal\node_modules\jest-circus\build\run.js:25:3)
    at runAndTransformResultsToJestFormat (C:\Scout\is24-finance-portal\node_modules\jest-circus\build\legacy-code-todo-rewrite\jestAdapterInit.js:176:21)
    at jestAdapter (C:\Scout\is24-finance-portal\node_modules\jest-circus\build\legacy-code-todo-rewrite\jestAdapter.js:109:19)
    at runTestInternal (C:\Scout\is24-finance-portal\node_modules\jest-runner\build\runTest.js:380:16)
    at runTest (C:\Scout\is24-finance-portal\node_modules\jest-runner\build\runTest.js:472:34)

**Comment by rodpatulski** [comment]
I have the same issue @tkosiorski have you figured this out?

**Comment by rodpatulski** [comment]
Hmm, that didn't work for me.
