### ISSUE TITLE
TypeError: clone.node.getBBox is not a function

### ISSUE THREAD

**Issue by maruwil** [apexcharts/react-apexcharts#52]
Hi, I have a console warning I was hoping someone could help me with.
When using apex charts heatmap I get a long callstack console warning.
I'm doing a smoke test on the component with jest to make sure it renders properly.
I also tested for the example code for React heatmap on the apex charts webpages and I get same warning.

`console.warn node_modules/apexcharts/dist/apexcharts.common.js:14260`
`       Possible Unhandled Promise Rejection: TypeError: clone.node.getBBox is not a function`
`       at new create (path\node_modules\apexcharts\dist\apexcharts.common.js:21109:30)`

And then the callstack continues a bit before another warning:

` console.warn node_modules/apexcharts/dist/apexcharts.common.js:14260`
 `Possible Unhandled Promise Rejection: TypeError: this.node.getScreenCTM is not a function` 
`at create.screenCTM (path\node_modules\apexcharts\dist\apexcharts.common.js:21342:41)`

And the callstack continues again.

Anyone have an idea of what might be the problem?

**Comment by junedchhipa** [comment]
Can you please create a codesandbox demo so I can see what causes it?

**Comment by junedchhipa** [comment]
Closing as no response.

**Comment by perkinss** [comment]
I'm also getting this error when I try to run tests using material ui createMount, which is using Enzyme mount.

``` Possible Unhandled Promise Rejection: TypeError: clone.node.getBBox is not a function```

Here is my radial bar code:
https://codesandbox.io/s/react-basic-example-gewe6?fontsize=14

I'm using createMount from Material UI.
As soon as I mount the component that has the radial chart, apexCharts complains with the above mentioned error.

I'd like to be able to mount the parent component because I want to have automated tests for a button click

**Comment by overlineink** [comment]
Hey @junedchhipa, I hope you're doing well. Since our team implemented the `apex-chart` all our unit tests (for components related with `apex`) get failed, here's the error message:

```terminal
Uncaught (in promise): TypeError: r.node.getBBox is not a function
    TypeError: r.node.getBBox is not a function

      at new create (../../node_modules/apexcharts/dist/apexcharts.common.js:6:363832)
      at create.bbox (../../node_modules/apexcharts/dist/apexcharts.common.js:6:364039)
      at t.value (../../node_modules/apexcharts/dist/apexcharts.common.js:6:25530)
      at ../../node_modules/apexcharts/dist/apexcharts.common.js:6:168277
          at Array.map (<anonymous>)
      at t.value (../../node_modules/apexcharts/dist/apexcharts.common.js:6:167680)
      at t.value (../../node_modules/apexcharts/dist/apexcharts.common.js:6:172523)
      at t.value (../../node_modules/apexcharts/dist/apexcharts.common.js:6:171960)
      at t.value (../../node_modules/apexcharts/dist/apexcharts.common.js:14:38662)
      at t.create (../../node_modules/apexcharts/dist/apexcharts.common.js:6:3406)
      at ../../node_modules/apexcharts/dist/apexcharts.common.js:14:37322
      at new ZoneAwarePromise (../../node_modules/zone.js/dist/zone.js:931:29)
      at t.value (../../node_modules/apexcharts/dist/apexcharts.common.js:14:36815)
      at ChartComponent.Object.<anonymous>.ChartComponent.render (../../node_modules/ng-apexcharts/bundles/ng:/ng-apexcharts/lib/chart/chart.component.ts:172:26)
      at ChartComponent.Object.<anonymous>.ChartComponent.createElement (../../node_modules/ng-apexcharts/bundles/ng:/ng-apexcharts/lib/chart/chart.component.ts:168:10)
      at AsapAction.work (../../node_modules/ng-apexcharts/bundles/ng:/ng-apexcharts/lib/chart/chart.component.ts:85:12)
      at AsapAction.Object.<anonymous>.AsyncAction._execute (../../node_modules/rxjs/src/internal/scheduler/AsyncAction.ts:122:12)
      at AsapAction.Object.<anonymous>.AsyncAction.execute (../../node_modules/rxjs/src/internal/scheduler/AsyncAction.ts:97:24)
      at AsapScheduler.Object.<anonymous>.AsapScheduler.flush (../../node_modules/rxjs/src/internal/scheduler/AsapScheduler.ts:17:26)
      at runIfPresent (../../node_modules/rxjs/src/internal/util/Immediate.ts:8:5)
      at ../../node_modules/rxjs/src/internal/util/Immediate.ts:16:34
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (../../node_modules/zone.js/dist/zone.js:391:26)
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvoke (../../node_modules/zone.js/dist/proxy.js:129:39)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (../../node_modules/zone.js/dist/zone.js:390:52)
      at Object.onInvoke (../../../packages/core/src/zone/ng_zone.ts:273:25)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (../../node_modules/zone.js/dist/zone.js:390:52)
      at Zone.Object.<anonymous>.Zone.run (../../node_modules/zone.js/dist/zone.js:150:43)
      at ../../node_modules/zone.js/dist/zone.js:910:34
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invokeTask (../../node_modules/zone.js/dist/zone.js:423:31)
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvokeTask (../../node_modules/zone.js/dist/proxy.js:160:39)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invokeTask (../../node_modules/zone.js/dist/zone.js:422:60)
      at Object.onInvokeTask (../../../packages/core/src/zone/ng_zone.ts:262:25)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invokeTask (../../node_modules/zone.js/dist/zone.js:422:60)
      at Zone.Object.<anonymous>.Zone.runTask (../../node_modules/zone.js/dist/zone.js:195:47)
      at drainMicroTaskQueue (../../node_modules/zone.js/dist/zone.js:601:35)
      at resolvePromise (../../node_modules/zone.js/dist/zone.js:852:31)
      at new ZoneAwarePromise (../../node_modules/zone.js/dist/zone.js:934:17)
      at t.value (../../node_modules/apexcharts/dist/apexcharts.common.js:14:36815)
      at ChartComponent.Object.<anonymous>.ChartComponent.render (../../node_modules/ng-apexcharts/bundles/ng:/ng-apexcharts/lib/chart/chart.component.ts:172:26)
      at ChartComponent.Object.<anonymous>.ChartComponent.createElement (../../node_modules/ng-apexcharts/bundles/ng:/ng-apexcharts/lib/chart/chart.component.ts:168:10)
      at AsapAction.work (../../node_modules/ng-apexcharts/bundles/ng:/ng-apexcharts/lib/chart/chart.component.ts:85:12)
      at AsapAction.Object.<anonymous>.AsyncAction._execute (../../node_modules/rxjs/src/internal/scheduler/AsyncAction.ts:122:12)
      at AsapAction.Object.<anonymous>.AsyncAction.execute (../../node_modules/rxjs/src/internal/scheduler/AsyncAction.ts:97:24)
      at AsapScheduler.Object.<anonymous>.AsapScheduler.flush (../../node_modules/rxjs/src/internal/scheduler/AsapScheduler.ts:17:26)
      at runIfPresent (../../node_modules/rxjs/src/internal/util/Immediate.ts:8:5)
      at ../../node_modules/rxjs/src/internal/util/Immediate.ts:16:34
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (../../node_modules/zone.js/dist/zone.js:391:26)
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvoke (../../node_modules/zone.js/dist/proxy.js:129:39)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (../../node_modules/zone.js/dist/zone.js:390:52)
      at Object.onInvoke (../../../packages/core/src/zone/ng_zone.ts:273:25)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (../../node_modules/zone.js/dist/zone.js:390:52)
      at Zone.Object.<anonymous>.Zone.run (../../node_modules/zone.js/dist/zone.js:150:43)
      at ../../node_modules/zone.js/dist/zone.js:910:34
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invokeTask (../../node_modules/zone.js/dist/zone.js:423:31)
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvokeTask (../../node_modules/zone.js/dist/proxy.js:160:39)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invokeTask (../../node_modules/zone.js/dist/zone.js:422:60)
      at Object.onInvokeTask (../../../packages/core/src/zone/ng_zone.ts:262:25)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invokeTask (../../node_modules/zone.js/dist/zone.js:422:60)
      at Zone.Object.<anonymous>.Zone.runTask (../../node_modules/zone.js/dist/zone.js:195:47)
      at drainMicroTaskQueue (../../node_modules/zone.js/dist/zone.js:601:35)
```

**Comment by StormBlade97** [comment]
Any update on this?

**Comment by junedchhipa** [comment]
Other users have fixed this error by mocking ApexCharts in their tests

```javascript
import ApexCharts from "apexcharts";
import ReactApexChart from "react-apexcharts";`

jest.mock("react-apexcharts", () =>
  jest.fn(() => {
    return null;
  })
);
jest.mock("apexcharts", () => ({
  exec: jest.fn(() => {
    return new Promise((resolve, reject) => {
      resolve("uri");
    });
  })
}));
```

https://github.com/apexcharts/ng-apexcharts/issues/48#issuecomment-667124436
https://github.com/apexcharts/react-apexcharts/issues/197#issuecomment-660125576

**Comment by karesztrk** [comment]
For anybody who is looking for mocks to suppress this warning. You can also add [jest-canvas-mock](https://www.npmjs.com/package/jest-canvas-mock) if you need a proper implementation behind the scenes.
```js
Object.defineProperty(global.SVGElement.prototype, 'getScreenCTM', {
  writable: true,
  value: jest.fn(),
});

Object.defineProperty(global.SVGElement.prototype, 'getBBox', {
  writable: true,
  value: jest.fn().mockReturnValue({
    x: 0,
    y: 0,
  }),
});

Object.defineProperty(global.SVGElement.prototype, 'getComputedTextLength', {
  writable: true,
  value: jest.fn().mockReturnValue(0),
});

Object.defineProperty(global.SVGElement.prototype, 'createSVGMatrix', {
  writable: true,
  value: jest.fn().mockReturnValue({
    x: 10,
    y: 10,
    inverse: () => {},
    multiply: () => {},
  }),
});
```
