### ISSUE TITLE
Cannot read properties of null (reading 'insertBefore') if uses text Annotation

### ISSUE THREAD

**Issue by IAleks94** [apexcharts/react-apexcharts#560]
if add text annotations to the chart options you'll get an error 
<img width="1510" alt="image" src="https://github.com/apexcharts/react-apexcharts/assets/57172661/d2af0323-682b-4480-b619-0f4f536fd306">

> Cannot read properties of null (reading 'insertBefore')
TypeError: Cannot read properties of null (reading 'insertBefore')
    at t.value (http://localhost:3000/static/js/bundle.js:3846:13)
    at http://localhost:3000/static/js/bundle.js:3784:13
    at Array.map (<anonymous>)
    at t.value (http://localhost:3000/static/js/bundle.js:3783:41)
    at http://localhost:3000/static/js/bundle.js:18236:82
    at new Promise (<anonymous>)
    at t.value (http://localhost:3000/static/js/bundle.js:18230:14)
    at http://localhost:3000/static/js/bundle.js:18183:13
    at new Promise (<anonymous>)
    at t.value (http://localhost:3000/static/js/bundle.js:18154:14)
    
   demo: https://github.com/IAleks94/apexcharts-demo

**Comment by junedchhipa** [comment]
Fixed in [commit](https://github.com/apexcharts/apexcharts.js/commit/939125fbc47980cf7ba349a964182ffae0041d8a)
Please for a new release of https://github.com/apexcharts/apexcharts.js
