### ISSUE TITLE
apexcharts.common.js:6 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'group') 

### ISSUE THREAD

**Issue by sai12-creator** [apexcharts/react-apexcharts#598]
hi everyone im getting very complex error actually in localhost react-apexchart working fine not giving any errors in console but coming to dev portal above error is throwing only in dev portal local is working fine  
apexcharts.common.js:6 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'group')
    at apexcharts.common.js:6:166282
    at Array.forEach (<anonymous>)
    at apexcharts.common.js:6:166243
    at Array.forEach (<anonymous>)
    at t.value (apexcharts.common.js:6:166209)
    at t.value (apexcharts.common.js:6:172254)
    at t.value (apexcharts.common.js:6:168242)
    at t.value (apexcharts.common.js:6:417928)
    at t.value (apexcharts.common.js:14:37913)
    at t.create (apexcharts.common.js:6:4486)
<img width="649" alt="error" src="https://github.com/apexcharts/react-apexcharts/assets/131845872/9ae898a7-a1eb-4857-a7f6-38a2d89ddf18">

**Comment by RodolfoRdz11** [comment]
If you are using react, it was fixed in react-apexcharts@1.4.1

**Comment by madebywitteveen** [comment]
I have something similar with another property 'map':

apexcharts-card:  Error: Cannot read properties of undefined (reading 'map')
    at eval (eval at _generateData (apexcharts-card.js?hacstag=331701152204:835:42497), <anonymous>:3:46)
    at Ia._generateData (apexcharts-card.js?hacstag=331701152204:835:42598)
    at Ia._updateHistory (apexcharts-card.js?hacstag=331701152204:835:38894)
    at apexcharts-card.js?hacstag=331701152204:908:3531
    at Array.map (<anonymous>)
    at tr._updateData (apexcharts-card.js?hacstag=331701152204:908:3486)
    at tr._firstDataLoad (apexcharts-card.js?hacstag=331701152204:835:77071)
    at tr._initialLoad (apexcharts-card.js?hacstag=331701152204:908:3176)



How can I fix this ?

thank, you

**Comment by DevelopJKong** [comment]
It seems like this issue is still problematic. How can it be resolved?

**Comment by seniordev-ca** [comment]
I am also getting the same error, in my case I am getting above error on the local as well. 
Any updates here?

**Comment by sai12-creator** [comment]
Dondrage to earlier version

**Comment by seniordev-ca** [comment]
> If you are using react, it was fixed in react-apexcharts@1.4.1

@RodolfoRdz11  I am on react-apexcharts@1.4.1, but still have the same error.

**Comment by seniordev-ca** [comment]
> Dondrage to earlier version

@sai12-creator , which version are you on? I am on the latest react-apexcharts@1.4.1 and I am still getting this error.
I also tried to use `group` property to use synchronized charts, but it never works.

**Comment by sai12-creator** [comment]
3.48

**Comment by RodolfoRdz11** [comment]
I'm using React, with the library react-apexcharts.
I found a nonsense fix, I have an object defaultChartOptions with all default options, obviuosly. Then I have a useEffect that sets the data in xaxis and yaxis, so I used spread operator to set data like this:

`	useEffect(() => {
		if (!_.isEmpty(areaChartData.graph_data)) {
			const oppositeMax = getMax([
				...areaChartData.graph_data.series?.[1]?.data,
				...areaChartData.graph_data.series?.[2]?.data
			], true)

			const oppositeMin = getMin([
				...areaChartData.graph_data.series?.[1]?.data,
				...areaChartData.graph_data.series?.[2]?.data
			])

			setOptions({
				...options,
				series: areaChartData.graph_data.series.map((serie: any) => ({
					...serie,
					data: serie.data.map((value: number) => value.toFixed(2))
				})),
				xaxis: {
					...options.xaxis,
					categories: areaChartData.graph_data.categories.map((category: string) => parseInt(category))
				},
				yaxis: [{
					...options?.yaxis?.[0],
					min: getMin(areaChartData.graph_data.series?.[0]?.data),
					max: getMax(areaChartData.graph_data.series?.[0]?.data),
				}, {
					...options?.yaxis?.[1],
					min: oppositeMin,
					max: oppositeMax,
				}, {
					...options?.yaxis?.[2],
					min: oppositeMin,
					max: oppositeMax,
				}]
			})
		}
	}, [areaChartData])`

The bug was caused by the yaxis attribute (I tried removing every attribute to find out what was causing the error), then I tried set the yaxis directly without spread operator and the error no longer appeared 

`	useEffect(() => {
		if (!_.isEmpty(areaChartData.graph_data)) {
			const oppositeMax = getMax([
				...areaChartData.graph_data.series?.[1]?.data,
				...areaChartData.graph_data.series?.[2]?.data
			], true)

			const oppositeMin = getMin([
				...areaChartData.graph_data.series?.[1]?.data,
				...areaChartData.graph_data.series?.[2]?.data
			])

			setOptions({
				...options,
				series: areaChartData.graph_data.series.map((serie: any) => ({
					...serie,
					data: serie.data.map((value: number) => value.toFixed(2))
				})),
				xaxis: {
					...options.xaxis,
					categories: areaChartData.graph_data.categories.map((category: string) => parseInt(category))
				},
				yaxis: [{
					title: {
						text: 'Monto',
						offsetY: -150,
						offsetX: 35,
						rotate: 360,
						style: {
							fontFamily: fontFamilies,
							fontWeight: 500,
							color: '#8892A0',
							fontSize: '12px'
						}
					},
					show: true,
					labels: {
						formatter: (val: number, opts?: any) => nFormatter(val, 1),
						offsetX: -45,
						style: {
							fontFamily: fontFamilies,
							fontWeight: 600,
							fontSize: '14px',
							colors: '#242C37'
						}
					},
					min: getMin(areaChartData.graph_data.series?.[0]?.data),
					max: getMax(areaChartData.graph_data.series?.[0]?.data),
				}, {
					opposite: true,
					title: {
						text: '',
						offsetY: 0,
						offsetX: 0,
						style: {
							fontFamily: fontFamilies,
							fontWeight: 500,
							color: '#8892A0',
							fontSize: '12px'
						}
					},

					show: true,
					labels: {
						formatter: (val: number, opts?: any) => nFormatter(val, 1),
						offsetX: -15,
						style: {
							fontFamily: fontFamilies,
							fontWeight: 600,
							fontSize: '14px',
							colors: '#242C37'
						}
					},
					min: oppositeMin,
					max: oppositeMax,
				}, {
					opposite: true,
					show: false,
					min: oppositeMin,
					max: oppositeMax,
				}]
			})
		}
	}, [areaChartData])`

**Comment by windoo2809** [comment]
any solutions?

**Comment by madebywitteveen** [comment]
The error on my side was with the nordpool integration but have no time yet to investigate

 

thanks

**Comment by madebywitteveen** [comment]
Nope, no solution yet. Thanks 


________________________________

**Comment by JackSacali** [comment]
I have a similar issue using react and apexcharts, I solved it using cloneDeep from lodash to pass the series array:
```
const chartOptions: ApexOptions = {
  series: cloneDeep(series),
  ...otherOptions,
};
```

**Comment by madebywitteveen** [comment]
Thanks 👍 


________________________________

**Comment by spartfin** [comment]
Same problem, nothing above helps, `vue 2.7.16`, `apexcharts 3.51.0`. It’s funny that the error never happened, and then it just appeared, from where it’s not clear.  Series looks like this:  `this.series = _.map(names, n => {
				return {
					techName: n,
					name: this.$t('project.' + n),
					data: _.values(this.activity[n]),
				}
			})`

**Comment by d0dge** [comment]
I'm having this issue too.  It doesn't prevent charts from rendering but it does seem to slow down that rendering quite a lot, which isn't great.

**Comment by AyushBawane** [comment]
one solution that worked for me is, add check on your component's top. check if data is undefined.

```
if(data === undefined) return ;
```

u can then may be memoize the component or parent according data change or how u want to render the component.

**Comment by leocharrua** [comment]
Hello, I had a similar error with angular:

node_modules_apexcharts_dist_apexcharts_common_js.js:2 TypeError: Cannot read properties of null (reading 'hidden')
    at apexcharts.common.js:14:37898
    at Array.forEach (<anonymous>)
    at t.value (apexcharts.common.js:14:37873)
    at t.create (apexcharts.common.js:6:4908)
    at apexcharts.common.js:14:37096
    at new ZoneAwarePromise (zone.js:2702:25)
    at t.value (apexcharts.common.js:14:21791)
    at ng-apexcharts.mjs:113:74
    at _ZoneDelegate.invoke (zone.js:369:28)
    at ZoneImpl.run (zone.js:111:43)

**Comment by madebywitteveen** [comment]
Ok thanks a lot 😄 


________________________________

**Comment by hdescottes** [comment]
Probably the same error, apexcharts 3.54.1 react-apexcharts 1.5.0
![image](https://github.com/user-attachments/assets/efdc3d99-4ac9-4d03-a2d0-174348f57380)
