### ISSUE TITLE
[ChartID] Cannot read properties of undefined (reading 'node')

### ISSUE THREAD

**Issue by mtr1990** [apexcharts/react-apexcharts#602]
Hi,

When I set id for chart:

```js
    chart: {
      id: 'dashboardChart',  // => here
      stacked: true,
    },
```

<img width="699" alt="image" src="https://github.com/apexcharts/react-apexcharts/assets/13531993/29ce468e-d6e7-4ce1-81c1-6093cd3d09f7">

```json
"apexcharts": "^3.49.1",  // => Not bug in 3.49.0
"react-apexcharts": "^1.4.1",
```

**Comment by xHeaven** [comment]
We have the same issue, we can also confirm that this bug got introduced in 3.49.1, the previous version didn't have this issue.

**Comment by ulisescarreonalvarez** [comment]
This happens randomly when we clone a clean repo and make a yarn install, sometimes it works sometimes not, but always is this library in the same version 1.4.1

**Comment by pnedelko** [comment]
Had the same issue, with 3.49.0 works fine.

**Comment by brianjlacy** [comment]
Same issue here.

Strange though, I had two different (identical) instances of my app running in dev mode on the same machine; one was rendering correctly and one was throwing the error mentioned above -- and then I closed the browser on the working instance and re-opened it, and it started failing also. Never could get either of them working again until I downgraded to 3.49.0, after which they started rendering properly.

**Comment by junedchhipa** [comment]
Can anyone create a codesandbox to reproduce this issue? I cannot reproduce it locally with `apexcharts@3.49.1` and `react-apexcharts@1.4.1`

**Comment by brianjlacy** [comment]
I'm not certain the behavior is completely consistent, so take this all with a grain of salt.

1. In the following example, when I omitted the `chart.id` property from the chart options on BOTH charts, the charts seemed to always render correctly.

```ts
import { ApexOptions } from "apexcharts";
import Chart from "react-apexcharts";

const ChartsComponent = () => {
  const barChartSeries = [
    {
      data: [10, 20, 70],
    },
  ];

  const barChartOptions: ApexOptions = {
    chart: {
      // id: "basic-bar",
    },
    xaxis: {
      categories: ["A", "B", "C"],
    },
  };

  const donutChartSeries = [10, 20, 70];

  const donutChartOptions: ApexOptions = {
    chart: {
      // id: "donut-chart",
      type: "donut",
    },
    labels: ["Series A", "Series B", "Series C"],
    responsive: [{
      breakpoint: 480,
      options: {
        chart: {
          width: 300,
        },
      },
    }],
  };

  return (
    <div>
      <Chart options={barChartOptions} series={barChartSeries} type="bar" width="320" />
      <Chart options={donutChartOptions} series={donutChartSeries} type="donut" width="320" />
    </div>
  );
};

export default ChartsComponent;
```

2. But when I _include_ the `chart.id` property, the charts crash the page.

3. Experimenting further -- if I remove the `responsive` property from the donut chart, then both charts render fine, EVEN with the `id` properties included.

Stay with me now... 😁 it's gonna get bumpy!

4. If I _move_ the `responsive` property you see in the example from the `donutChartOptions`, to the `barChartOptions` -- with the `id` properties still in place -- then the Donut Chart renders, but the Bar Chart does not.

5. I removed the `id` property from the Bar Chart _only_, and the bar chart now renders (as well as the rest of the page!).

6. After restoring the `id` property (resetting the state back to #4) -- I _swapped_ the position of the bar chart and donut chart:

```
    <div>
      <Chart options={barChartOptions} series={barChartSeries} type="bar" width="320" />
      <Chart options={donutChartOptions} series={donutChartSeries} type="donut" width="320" />
    </div>
```

**Now, the whole page crashes again.**

7. Following the earlier procedure, I moved the `response` property back to the `donutChartOptions`. The Bar Chart now renders, and the Donut Chart does not.

8. Removing the `id` property from the Bar Chart now makes now difference (as we might expect). But removing the `id` from the Donut Chart options, the whole page renders correctly again.

**Comment by katerberg** [comment]
Did you find a way around this? I'm seeing it with apexcharts 4.x as well

**Comment by kabuye-dennis** [comment]
faced the same issue after upgrading to later versions. I downgraded to version  `3.49.0`, to get it fixed. I hope this helps @katerberg

**Comment by katerberg** [comment]
Yeah, we also opted not to upgrade, which is disappointing.

**Comment by junedchhipa** [comment]
A reproducible codesandbox will be helpful. Can anyone create it, please?

**Comment by nRoger-Env** [comment]
I also have this bug in my app. For me, this happen when I resize the window of my internet browser.
The bug occur in apexcharts.common.js.

Error:
```
Uncaught TypeError TypeError: Cannot read properties of undefined (reading 'node')
    at value (c:\Users\rogni01\source\repos\Carte_Vue\Carte_Vue_TS\node_modules\apexcharts\dist\apexcharts.common.js:14:20618)
    at value (c:\Users\rogni01\source\repos\Carte_Vue\Carte_Vue_TS\node_modules\apexcharts\dist\apexcharts.common.js:14:20361)
    at <anonymous> (c:\Users\rogni01\source\repos\Carte_Vue\Carte_Vue_TS\node_modules\apexcharts\dist\apexcharts.common.js:14:43822)
    at value (c:\Users\rogni01\source\repos\Carte_Vue\Carte_Vue_TS\node_modules\apexcharts\dist\apexcharts.common.js:14:43781)
    at <anonymous> (c:\Users\rogni01\source\repos\Carte_Vue\Carte_Vue_TS\node_modules\apexcharts\dist\apexcharts.common.js:14:47793)
    --- setTimeout ---
    at value (c:\Users\rogni01\source\repos\Carte_Vue\Carte_Vue_TS\node_modules\apexcharts\dist\apexcharts.common.js:14:47714)
    at value (c:\Users\rogni01\source\repos\Carte_Vue\Carte_Vue_TS\node_modules\apexcharts\dist\apexcharts.common.js:14:47941)
TypeError: Cannot read properties of undefined (reading 'node')
Trace de la pile :
 >  at t2.value (http://localhost:5173/node_modules/.vite/deps/apexcharts.js?v=2dfc1d69:8612:74)
 >    at t2.value (http://localhost:5173/node_modules/.vite/deps/apexcharts.js?v=2dfc1d69:8606:667)
 >    at http://localhost:5173/node_modules/.vite/deps/apexcharts.js?v=2dfc1d69:8752:26
 >    at new Promise (<anonymous>)
 >    at t2.value (http://localhost:5173/node_modules/.vite/deps/apexcharts.js?v=2dfc1d69:8751:16)
 >    at http://localhost:5173/node_modules/.vite/deps/apexcharts.js?v=2dfc1d69:8839:81
```

Apex charts js version 3.54.1 in a vue app.

**Comment by jonoirwinrsa** [comment]
`Cannot read properties of undefined (reading 'node')` was happening to me too on `apexcharts@^4.5.0`. Downgraded to `3.49.0` and it works fine

**Comment by jonoirwinrsa** [comment]
As far as I can see, the issue comes from:

```
      } }, { key: "clearDomElements", value: function(t3) {
        var e2 = this, i2 = t3.isUpdating, a2 = this.w.globals.dom.Paper.node;
```

However, monkey patching that function seems to kick the can down the road

**Comment by Getsumi3** [comment]
> As far as I can see, the issue comes from:
> 
> ```
>       } }, { key: "clearDomElements", value: function(t3) {
>         var e2 = this, i2 = t3.isUpdating, a2 = this.w.globals.dom.Paper.node;
> ```
> 
> However, monkey patching that function seems to kick the can down the road.
> 
> Removing the responsive options from my options object worked for me - no more `Cannot read properties of undefined (reading 'node')`

Can confirm that removing `responsive` from `options` also worked for me 

`apexcharts: 3.54.1`
`react-apexcharts: 1.4.4`

**Comment by SagarSatav** [comment]
Cannot read properties of undefined (reading 'node') was happening to me too on "apexcharts":^4.5.0. and  "react-apexcharts": "^1.7.0.", Downgraded to 3.42.0,and 1.4.0 then it works fine

**Comment by josemonkey** [comment]
I'm just curious if there been any additional investigation into this?

I know this doesn't match others experience here, but for me I observe the following:

- I was using `apexcharts@5.10.6` and `react-apexcharts@2.1.0` and everything was working well.
- When I updated to using `apexcharts@5.13.0` I first started seeing the `Cannot read properties of undefined (reading 'node')` error message
- I didn't have time to diagnose, so I rolled back to 5.10.6. (Error went away.)
- Today, I tried updating to `apexcharts@5.15.0`, but I am seeing the error again. 

I will probably just pin my dependency to the exact version that doesn't give the error for now (i.e., `apexcharts@5.10.6`), but it seems like there's definitely something going on here. 

FWIW, I haven't been able to reproduce this a minimal environment just yet, but I'm trying. (So far, I can't make the error happen outside of my project, which is frustrating!)

**Comment by acenturionqisur** [comment]
I'm having the same issue. I think ApexCharts is disappearing from the DOM, so when it tries to evaluate, it throws this error. I'm not entirely sure if this error is related.
I've already tried using different versions, adding a delay, using chartRef, managing it with useState, and adding a loading state, but I keep getting the same error.
This happens specifically when you display the chart, close it, and then try to open it again.


<img width="620" height="274" alt="Image" src="https://github.com/user-attachments/assets/93226c5e-1b23-4715-8260-0337fa0cc06a" />

<img width="609" height="478" alt="Image" src="https://github.com/user-attachments/assets/8f503d00-40c3-4c99-97e0-a8e60b88bf84" />

when i debug the code 

<img width="538" height="109" alt="Image" src="https://github.com/user-attachments/assets/5f6a0d89-ef92-43d7-b87b-4dfdef4c82cc" />

<img width="554" height="288" alt="Image" src="https://github.com/user-attachments/assets/22de9d23-f51b-41e6-b0a7-74fceb246804" />

<img width="464" height="207" alt="Image" src="https://github.com/user-attachments/assets/e2253c56-d3a3-4674-b720-f9e488fc6020" />

<img width="365" height="180" alt="Image" src="https://github.com/user-attachments/assets/2dd29499-0317-4cf9-981f-ad9c1baba26e" />

**Comment by SagarSatav** [comment]
Uncaught TypeError: Cannot read properties of null (reading 'node')

getting this error in latest version too

**Comment by junedchhipa** [comment]
The crash `Cannot read properties of undefined (reading 'node')` happened during chart teardown. `w.dom.Paper` is only created once setupElements() runs, and `render()/update()` bail out early when the chart's element isn't connected to the DOM (!element.isConnected). 

**The fix**

**apexcharts 5.15.1:** clearDomElements() now guards against a missing Paper, destroy() guards the instance registry and clears any pending resize timer. This removes the crash at the source for all wrappers (React, Vue, Angular, vanilla).
**react-apexcharts 2.1.1:** the unmount cleanup is now wrapped so a teardown error can never crash the React tree.

If anyone still hits this on apexcharts@5.15.1 + react-apexcharts@2.1.1, please comment with a minimal reproduction and I'll reopen.

**Comment by josemonkey** [comment]
I just tried upgrading to `apexcharts@5.15.1` and `react-apexcharts@2.1.1`, but I still see the error. I'll see if I can set up a minimal reproduction, but so far I've had trouble isolating it.

By the way, I just noticed that the error goes away when I turn off `React.StrictMode` so all signs point to a life cycle issue that is being detected by a quick render, unmount, re-render. (StrictMode doing its job, once again! lol)

Partial console output follows, in case it is helpful.

```
react-apexcharts.js?v=0b77aea7:5500 Uncaught TypeError: Cannot read properties of null (reading 'node')
    at runMaskReveal (react-apexcharts.js?v=0b77aea7:5500:17)
    at react-apexcharts.js?v=0b77aea7:5535:5
runMaskReveal @ react-apexcharts.js?v=0b77aea7:5500
(anonymous) @ react-apexcharts.js?v=0b77aea7:5535
requestAnimationFrame
requestAnimationFrame @ react-apexcharts.js?v=0b77aea7:504
animateDraw @ react-apexcharts.js?v=0b77aea7:5533
renderPaths @ react-apexcharts.js?v=0b77aea7:6107
_handlePaths @ react-apexcharts.js?v=0b77aea7:26753
draw @ react-apexcharts.js?v=0b77aea7:26613
plotChartType @ react-apexcharts.js?v=0b77aea7:12021
create @ react-apexcharts.js?v=0b77aea7:18104
(anonymous) @ react-apexcharts.js?v=0b77aea7:18025
render @ react-apexcharts.js?v=0b77aea7:17991
(anonymous) @ react-apexcharts.js?v=0b77aea7:29709
react_stack_bottom_frame @ react-dom_client.js?v=6cbd7c90:12904
runWithFiberInDEV @ react-dom_client.js?v=6cbd7c90:851
commitHookEffectListMount @ react-dom_client.js?v=6cbd7c90:6617
commitHookPassiveMountEffects @ react-dom_client.js?v=6cbd7c90:6652
commitPassiveMountOnFiber @ react-dom_client.js?v=6cbd7c90:7618
recursivelyTraversePassiveMountEffects @ react-dom_client.js?v=6cbd7c90:7606
commitPassiveMountOnFiber @ react-dom_client.js?v=6cbd7c90:7672
recursivelyTraversePassiveMountEffects @ react-dom_client.js?v=6cbd7c90:7606
commitPassiveMountOnFiber @ react-dom_client.js?v=6cbd7c90:7617
recursivelyTraversePassiveMountEffects @ react-dom_client.js?v=6cbd7c90:7606
...[truncated]
```

**Comment by josemonkey** [comment]
Ok, I have steps to reproduce the error using the react-apexcharts example app.

**Important note**: When you want to see the error, make sure you view the "**Area Chart**" example. You will need to select this from the left nav in the example app (second option) since the default is the "Line Chart."

### Steps to reproduce

#### 1. Install and Run Example App
Clone the react-apexcharts repo locally:
```
git clone https://github.com/apexcharts/react-apexcharts.git
```

The version at the moment is 2.1.1, which is expected to work per comments above.

Get everything set up initially to ensure it is working as expected. So:
```
cd react-apexcharts
npm install
```

Then:
```
cd example
npm install
```

While still in the example folder, run the example app:
```
npm run dev
```

Ensure everything works as expected, no error should show in the console at this time.

#### 2. Upgrade to Latest Version of apexcharts

First, bring react-apexcharts and the example app up to the latest apexcharts (5.15.1) since their package-lock.json files reference 5.10.1

So, in both the base react-apexcharts folder AND in the examples subfolder, do this:
```
npm i apexcharts@latest
```

If you want, you can run the example app to make sure it still works and doesn't produce an error. It should be fine, though.
```
npm run dev
```

#### 3. Enable `React.StrictMode` to see the error on the Area Chart example

We need to edit the example app to turn on strict mode. So open up `example/src/index.jsx` and change this line:
```javascript
createRoot(document.getElementById("root")).render(<App />);
```

to 
```javascript
createRoot(document.getElementById("root")).render(
    <React.StrictMode>
            <App />
    </React.StrictMode>,
);
```

Start the example app:
```
npm run dev
```

Open the app, and navigate to the Area chart example. **You should now see the error in the console.** 

```
react-apexcharts.js?v=e39114fe:6684 Uncaught TypeError: Cannot read properties of null (reading 'node')
    at runMaskReveal (react-apexcharts.js?v=e39114fe:6684:20)
    at react-apexcharts.js?v=e39114fe:6724:9
runMaskReveal @ react-apexcharts.js?v=e39114fe:6684
(anonymous) @ react-apexcharts.js?v=e39114fe:6724
requestAnimationFrame
requestAnimationFrame @ react-apexcharts.js?v=e39114fe:557
animateDraw @ react-apexcharts.js?v=e39114fe:6722
renderPaths @ react-apexcharts.js?v=e39114fe:7405
_handlePaths @ react-apexcharts.js?v=e39114fe:33318
draw @ react-apexcharts.js?v=e39114fe:33135
plotChartType @ react-apexcharts.js?v=e39114fe:15018
create @ react-apexcharts.js?v=e39114fe:22397
(anonymous) @ react-apexcharts.js?v=e39114fe:22291
render @ react-apexcharts.js?v=e39114fe:22240
(anonymous) @ react-apexcharts.js?v=e39114fe:37018
commitHookEffectListMount @ chunk-CJSRII5H.js?v=b229cd3e:16963
commitPassiveMountOnFiber @ chunk-CJSRII5H.js?v=b229cd3e:18206
commitPassiveMountEffects_complete @ chunk-CJSRII5H.js?v=b229cd3e:18179
commitPassiveMountEffects_begin @ chunk-CJSRII5H.js?v=b229cd3e:18169
commitPassiveMountEffects @ chunk-CJSRII5H.js?v=b229cd3e:18159
flushPassiveEffectsImpl @ chunk-CJSRII5H.js?v=b229cd3e:19543
flushPassiveEffects @ chunk-CJSRII5H.js?v=b229cd3e:19500
commitRootImpl @ chunk-CJSRII5H.js?v=b229cd3e:19469
commitRoot @ chunk-CJSRII5H.js?v=b229cd3e:19330
performSyncWorkOnRoot @ chunk-CJSRII5H.js?v=b229cd3e:18948
flushSyncCallbacks @ chunk-CJSRII5H.js?v=b229cd3e:9166
(anonymous) @ chunk-CJSRII5H.js?v=b229cd3e:18677
react-apexcharts.js?v=e39114fe:6684 Uncaught TypeError: Cannot read properties of null (reading 'node')
    at runMaskReveal (react-apexcharts.js?v=e39114fe:6684:20)
    at react-apexcharts.js?v=e39114fe:6724:9
runMaskReveal @ react-apexcharts.js?v=e39114fe:6684
(anonymous) @ react-apexcharts.js?v=e39114fe:6724
requestAnimationFrame
requestAnimationFrame @ react-apexcharts.js?v=e39114fe:557
animateDraw @ react-apexcharts.js?v=e39114fe:6722
renderPaths @ react-apexcharts.js?v=e39114fe:7405
_handlePaths @ react-apexcharts.js?v=e39114fe:33318
draw @ react-apexcharts.js?v=e39114fe:33135
plotChartType @ react-apexcharts.js?v=e39114fe:15018
create @ react-apexcharts.js?v=e39114fe:22397
(anonymous) @ react-apexcharts.js?v=e39114fe:22291
render @ react-apexcharts.js?v=e39114fe:22240
(anonymous) @ react-apexcharts.js?v=e39114fe:37018
commitHookEffectListMount @ chunk-CJSRII5H.js?v=b229cd3e:16963
commitPassiveMountOnFiber @ chunk-CJSRII5H.js?v=b229cd3e:18206
commitPassiveMountEffects_complete @ chunk-CJSRII5H.js?v=b229cd3e:18179
commitPassiveMountEffects_begin @ chunk-CJSRII5H.js?v=b229cd3e:18169
commitPassiveMountEffects @ chunk-CJSRII5H.js?v=b229cd3e:18159
flushPassiveEffectsImpl @ chunk-CJSRII5H.js?v=b229cd3e:19543
flushPassiveEffects @ chunk-CJSRII5H.js?v=b229cd3e:19500
commitRootImpl @ chunk-CJSRII5H.js?v=b229cd3e:19469
commitRoot @ chunk-CJSRII5H.js?v=b229cd3e:19330
performSyncWorkOnRoot @ chunk-CJSRII5H.js?v=b229cd3e:18948
flushSyncCallbacks @ chunk-CJSRII5H.js?v=b229cd3e:9166
(anonymous) @ chunk-CJSRII5H.js?v=b229cd3e:18677
```

**Comment by josemonkey** [comment]
I see that @junedchhipa addressed this just now and that apexcharts@5.15.2 includes this change. I can verify this resolves the problem for me. Thanks, Juned.

**Comment by acenturionqisur** [comment]
@junedchhipa I updated the packages (apex and react-apex) and got this error. I'm not sure if it's related, because before this, I was always getting an 'undefined reading node' error.

<img width="270" height="195" alt="Image" src="https://github.com/user-attachments/assets/69830010-2329-4cb2-91cc-a0f302fff298" />

<img width="631" height="353" alt="Image" src="https://github.com/user-attachments/assets/b673ae33-05ca-4311-a824-6348fb270028" />

<img width="635" height="483" alt="Image" src="https://github.com/user-attachments/assets/20c34826-8a69-4718-8b96-082cc7fafaf8" />

<img width="596" height="156" alt="Image" src="https://github.com/user-attachments/assets/fd13fbf5-7a2f-4e7f-aba4-ca2c47853de6" />
